---
plugin: gcp_compute
projects:
  - saravana95
auth_kind: serviceaccount
service_account_file: /var/lib/jenkins/workspace/desktop/ansible/service-account.json
groups:
  desktop: "'desktop' in name"
  tomcat: "'tomcat' in name"
  apache2: "'apache2' in name"



